services:
  - type: web
    name: ttn-influx
    runtime: node
    plan: free
    region: singapore

    repo: https://github.com/mirza4509044-ship-it/ttn-influx
    buildCommand: "npm install"
    startCommand: "node index.js"

    envVars:
      - key: INFLUX_URL
        sync: false
      - key: INFLUX_TOKEN
        sync: false
      - key: INFLUX_ORG
        sync: false
      - key: INFLUX_BUCKET
        sync: false

      - key: TTN_MQTT_SERVER
        sync: false
      - key: TTN_USERNAME
        sync: false
      - key: TTN_PASSWORD
        sync: false

    autoDeployTrigger: commit



